language: rust
matrix:
  include:
    #- rust: stable # TODO: Re-enable after 1.36 is released.
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
