[package]
name = "px4"
version = "0.1.0"
authors = ["Mara Bos <m-ou.se@m-ou.se>"]

[lib]
name = "px4"
path = "src/lib.rs"

[[example]]
name = "demo"
crate-type = ["cdylib"]
path = "example/main.rs"

[dependencies]
log = "*"
